baseURL      = "https://thekarchan.github.io/thewindboy/"
title        = "Kar's Blog"
theme        = "hugo-bearblog-master"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[permalinks]
  posts = "/posts/:contentbasename/"
  blog = "/blog/:contentbasename/"

[menu]
  [[menu.main]]
    name = "Latest"
    pageRef = "/latest"
    weight = 1
  [[menu.main]]
    name = "Parade"
    pageRef = "/parade"
    weight = 2
  [[menu.main]]
    name = "Bird"
    pageRef = "/bird"
    weight = 3
  [[menu.main]]
    name = "Flux"
    pageRef = "/flux"
    weight = 4

[params]
  description = "A Nothing Big Blog"
  author = "Kar Chan"
  favicon = "favicon.svg"
  customCSS = ["custom.css"]
  mainSections = ["blog"] 
  listSummaries = true

[services]
  [services.googleAnalytics]
    ID = "G-09506ENLJ2"