baseURL      = "https://thekarchan.github.io/thewindboy/"
title        = "The Garden of Ants"
theme        = "hugo-bearblog-master"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
hasCJKLanguage = true

[permalinks]
  posts = "/posts/:contentbasename/"
  blog = "/blog/:contentbasename/"

[menu]
  [[menu.main]]
    name = "Latest"
    url = "/latest/"
    weight = 1
  [[menu.main]]
    name = "Parade"
    url = "/"
    weight = 2
  [[menu.main]]
    name = "Bird"
    url = "/bird/"
    weight = 3

    
[params]
  description = "A Nothing Big Blog"
  author = "Kar Chan"
  customCSS = ["css/custom.css"]
  # 明确文章来源目录。如果你在 content 下的文件夹改为了 blog，请将此处改为 ["blog"]，并将上方菜单的 url 改为 "/thewindboy/blog/"
  mainSections = ["blog"] 

  [params.giscus]
    enable = true
    repo    = "thekarchan/thewindboy"
    repoid  = "R_kgDORL52rw"
    category = "General"
    categoryid = ""
    mapping = "pathname"
    theme   = "light"

[services]
  [services.googleAnalytics]
    ID = "G-09506ENLJ2"