baseURL      = "https://thekarchan.github.io/thewindboy/"
title        = "The Ant's Garden"
theme        = "hugo-bearblog-master"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
hasCJKLanguage = true

[permalinks]
  posts = "/posts/:contentbasename/"
  blog = "/blog/:contentbasename/"

[menu]
  [[menu.main]]
    name = "Latest"
    pageRef = "/latest"
    weight = 1
  [[menu.main]]
    name = "Parade"
    pageRef = "/"
    weight = 2
  [[menu.main]]
    name = "Bird"
    pageRef = "/bird"
    weight = 3

[params]
  description = "A Nothing Big Blog"
  author = "Kar Chan"
  customCSS = ["css/custom.css"]
  mainSections = ["blog"] 
  listSummaries = true

  [params.giscus]
    enable = true
    repo    = "thekarchan/thewindboy"
    repoid  = "R_kgDORL52rw"
    category = "General"
    categoryid = ""
    mapping = "pathname"
    theme   = "light"

[services]
  [services.googleAnalytics]
    ID = "G-09506ENLJ2"