backend:
  name: github
  repo: thekarchan/thewindboy
  branch: source
  base_url: https://oauth.mcptutorial.top
  auth_endpoint: auth

# 如需本地调试可启用（运行 decap-server）
local_backend: true

site_url: https://thekarchan.github.io/thewindboy/
display_url: https://thekarchan.github.io/thewindboy/

media_folder: static/uploads
public_folder: /thewindboy/uploads

locale: zh_Hans

collections:
  - name: posts
    label: 文章
    label_singular: 文章
    folder: content/posts
    create: true
    delete: true
    extension: md
    format: frontmatter
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{year}}-{{month}}-{{day}} · {{title}}'
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 创建时间, name: date, widget: datetime, format: 'YYYY-MM-DDTHH:mm:ssZ', date_format: 'YYYY-MM-DD', time_format: 'HH:mm', picker_utc: false }
      - { label: 发布时间, name: publishDate, widget: datetime, required: false, format: 'YYYY-MM-DDTHH:mm:ssZ', date_format: 'YYYY-MM-DD', time_format: 'HH:mm', picker_utc: false }
      - { label: 草稿, name: draft, widget: boolean, default: false }
      - label: 标签
        name: tags
        widget: list
        required: false
        field: { label: 标签, name: tag, widget: string }
      - { label: 正文, name: body, widget: markdown }
